TEMPLATES = [
    "Scout path from {s} to {g}, keep safe altitude.",
    "Operate from {s} to {g}, maintaining safe altitude.",
    "Head from {s} to {g}, replan if occupied.",
    "Objective: Move from {s} to {g} and return safely.",
    "Go the UAV from {s} to {g}.",
    "Task: Travel between {s} and {g}, stay within safe zones.",
    "Mission: Head the drone from {s} to {g}, then finish by landing.",
    "Scout path from {s} to {g}, keep constant height.",
    "Survey the area from {s} until reaching {g}.",
    "Mission: Dispatch the drone from {s} to {g}, then finish by landing.",
    "Pilot the UAV from {s} to {g}.",
    "Objective: Control from {s} to {g} and descend.",
    "Go from {s} to {g}, maintaining altitude 1.0 meters.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Task: Move between {s} and {g}, stay clear of hazards.",
    "Task: Navigate between {s} and {g}, stay away from danger.",
    "Mission: Dispatch the drone from {s} to {g}, then touch down.",
    "Control from {s} to {g}, maintaining altitude 1.0 meters.",
    "Task: Move between {s} and {g}, stay away from danger.",
    "Control from {s} to {g}, maintaining altitude 1.0 meters.",
    "Go the UAV from {s} to {g}.",
    "Head from {s} to {g}, replan if not clear.",
    "Send from {s} to {g}, maintaining 1 meter height.",
    "Objective: Fly from {s} to {g} and touch down.",
    "Start at {s}, Head to {g}, then land.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Survey the area from {s} until reaching {g}.",
    "Start at {s}, Operate to {g}, then return safely.",
    "Operate from {s} to {g}, avoiding restricted regions.",
    "Go from {s} to {g}, avoiding barriers.",
    "Mission: Dispatch the drone from {s} to {g}, then land.",
    "Mission: Send the drone from {s} to {g}, then return safely.",
    "Survey the area from {s} until reaching {g}.",
    "Travel the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep constant height.",
    "Control from {s} to {g}, avoiding danger areas.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Head from {s} to {g}, replan if obstructed.",
    "Operate the UAV from {s} to {g}.",
    "Mission: Operate the drone from {s} to {g}, then descend.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Navigate from {s} to {g}, maintaining 1 meter height.",
    "Move the UAV from {s} to {g}.",
    "Mission: Travel the drone from {s} to {g}, then land.",
    "Pilot from {s} to {g}, maintaining constant height.",
    "Scout path from {s} to {g}, keep constant height.",
    "Task: Direct between {s} and {g}, stay safe.",
    "Pilot from {s} to {g}, maintaining low altitude.",
    "Survey the area from {s} until reaching {g}.",
    "Move the UAV from {s} to {g}.",
    "Control from {s} to {g}, avoiding no-fly zones.",
    "Task: Travel between {s} and {g}, stay clear of hazards.",
    "Start at {s}, Fly to {g}, then finish by landing.",
    "Objective: Move from {s} to {g} and touch down.",
    "Objective: Dispatch from {s} to {g} and finish by landing.",
    "Head from {s} to {g}, replan if blocked.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Task: Fly between {s} and {g}, stay safe.",
    "Navigate the UAV from {s} to {g}.",
    "Task: Move between {s} and {g}, stay away from danger.",
    "Start at {s}, Move to {g}, then descend.",
    "Move the UAV from {s} to {g}.",
    "Start at {s}, Head to {g}, then finish by landing.",
    "Fly the UAV from {s} to {g}.",
    "Objective: Fly from {s} to {g} and touch down.",
    "Survey the area from {s} until reaching {g}.",
    "Objective: Go from {s} to {g} and return safely.",
    "Mission: Operate the drone from {s} to {g}, then finish by landing.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Survey the area from {s} until reaching {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Mission: Navigate the drone from {s} to {g}, then finish by landing.",
    "Control from {s} to {g}, maintaining altitude 1.0 meters.",
    "Head from {s} to {g}, replan if obstructed.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Control from {s} to {g}, avoiding obstacles.",
    "Head from {s} to {g}, replan if not clear.",
    "Start at {s}, Go to {g}, then touch down.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Move the UAV from {s} to {g}.",
    "Mission: Fly the drone from {s} to {g}, then descend.",
    "Task: Pilot between {s} and {g}, stay safe.",
    "Head from {s} to {g}, replan if blocked.",
    "Fly from {s} to {g}, avoiding barriers.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Head from {s} to {g}, maintaining a steady altitude.",
    "Go from {s} to {g}, avoiding no-fly zones.",
    "Direct the UAV from {s} to {g}.",
    "Control from {s} to {g}, avoiding restricted regions.",
    "Objective: Move from {s} to {g} and descend.",
    "Go from {s} to {g}, avoiding danger areas.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Task: Move between {s} and {g}, stay safe.",
    "Fly from {s} to {g}, avoiding no-fly zones.",
    "Head from {s} to {g}, replan if unsafe.",
    "Move the UAV from {s} to {g}.",
    "Go from {s} to {g}, avoiding no-fly zones.",
    "Direct the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Head the UAV from {s} to {g}.",
    "Move the UAV from {s} to {g}.",
    "Start at {s}, Control to {g}, then return safely.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Head from {s} to {g}, replan if blocked.",
    "Head from {s} to {g}, replan if occupied.",
    "Dispatch from {s} to {g}, avoiding danger areas.",
    "Objective: Travel from {s} to {g} and land.",
    "Mission: Fly the drone from {s} to {g}, then descend.",
    "Go the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Objective: Go from {s} to {g} and land.",
    "Objective: Send from {s} to {g} and descend.",
    "Send from {s} to {g}, maintaining constant height.",
    "Scout path from {s} to {g}, keep constant height.",
    "Move from {s} to {g}, avoiding no-fly zones.",
    "Start at {s}, Send to {g}, then descend.",
    "Start at {s}, Dispatch to {g}, then touch down.",
    "Go from {s} to {g}, maintaining safe altitude.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Objective: Fly from {s} to {g} and finish by landing.",
    "Head from {s} to {g}, replan if occupied.",
    "Survey the area from {s} until reaching {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Go the UAV from {s} to {g}.",
    "Start at {s}, Pilot to {g}, then land.",
    "Objective: Pilot from {s} to {g} and return safely.",
    "Direct the UAV from {s} to {g}.",
    "Task: Send between {s} and {g}, stay away from danger.",
    "Start at {s}, Move to {g}, then touch down.",
    "Mission: Pilot the drone from {s} to {g}, then finish by landing.",
    "Head from {s} to {g}, replan if occupied.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Mission: Head the drone from {s} to {g}, then finish by landing.",
    "Objective: Direct from {s} to {g} and return safely.",
    "Survey the area from {s} until reaching {g}.",
    "Direct from {s} to {g}, avoiding no-fly zones.",
    "Task: Operate between {s} and {g}, stay cautious.",
    "Mission: Go the drone from {s} to {g}, then land.",
    "Head from {s} to {g}, replan if blocked.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Control from {s} to {g}, avoiding barriers.",
    "Objective: Move from {s} to {g} and finish by landing.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Head from {s} to {g}, replan if blocked.",
    "Operate from {s} to {g}, maintaining a steady altitude.",
    "Head the UAV from {s} to {g}.",
    "Task: Go between {s} and {g}, stay safe.",
    "Survey the area from {s} until reaching {g}.",
    "Head from {s} to {g}, replan if not clear.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Dispatch from {s} to {g}, maintaining safe altitude.",
    "Head from {s} to {g}, replan if blocked.",
    "Survey the area from {s} until reaching {g}.",
    "Objective: Head from {s} to {g} and finish by landing.",
    "Objective: Pilot from {s} to {g} and touch down.",
    "Survey the area from {s} until reaching {g}.",
    "Dispatch from {s} to {g}, maintaining 1 meter height.",
    "Mission: Fly the drone from {s} to {g}, then land.",
    "Survey the area from {s} until reaching {g}.",
    "Control from {s} to {g}, avoiding restricted regions.",
    "Direct from {s} to {g}, avoiding obstacles.",
    "Move the UAV from {s} to {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Head from {s} to {g}, replan if blocked.",
    "Direct from {s} to {g}, maintaining low altitude.",
    "Fly the UAV from {s} to {g}.",
    "Navigate from {s} to {g}, maintaining constant height.",
    "Pilot from {s} to {g}, avoiding barriers.",
    "Head from {s} to {g}, replan if occupied.",
    "Mission: Operate the drone from {s} to {g}, then land.",
    "Mission: Direct the drone from {s} to {g}, then descend.",
    "Direct from {s} to {g}, avoiding hazards.",
    "Move from {s} to {g}, avoiding hazards.",
    "Mission: Control the drone from {s} to {g}, then land.",
    "Navigate the UAV from {s} to {g}.",
    "Fly the UAV from {s} to {g}.",
    "Send from {s} to {g}, avoiding hazards.",
    "Travel from {s} to {g}, avoiding restricted regions.",
    "Start at {s}, Fly to {g}, then return safely.",
    "Control from {s} to {g}, avoiding danger areas.",
    "Send from {s} to {g}, maintaining constant height.",
    "Objective: Control from {s} to {g} and finish by landing.",
    "Start at {s}, Fly to {g}, then land.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Mission: Fly the drone from {s} to {g}, then touch down.",
    "Go from {s} to {g}, avoiding danger areas.",
    "Control the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Travel from {s} to {g}, maintaining a steady altitude.",
    "Task: Control between {s} and {g}, stay cautious.",
    "Fly the UAV from {s} to {g}.",
    "Task: Direct between {s} and {g}, stay cautious.",
    "Head from {s} to {g}, replan if occupied.",
    "Objective: Control from {s} to {g} and return safely.",
    "Objective: Go from {s} to {g} and return safely.",
    "Task: Navigate between {s} and {g}, stay safe.",
    "Task: Send between {s} and {g}, stay clear of hazards.",
    "Mission: Pilot the drone from {s} to {g}, then finish by landing.",
    "Head from {s} to {g}, replan if unsafe.",
    "Mission: Travel the drone from {s} to {g}, then land.",
    "Task: Control between {s} and {g}, stay safe.",
    "Head from {s} to {g}, replan if blocked.",
    "Head from {s} to {g}, replan if unsafe.",
    "Head from {s} to {g}, maintaining low altitude.",
    "Mission: Pilot the drone from {s} to {g}, then touch down.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Start at {s}, Navigate to {g}, then descend.",
    "Start at {s}, Operate to {g}, then descend.",
    "Objective: Direct from {s} to {g} and finish by landing.",
    "Survey the area from {s} until reaching {g}.",
    "Task: Operate between {s} and {g}, stay within safe zones.",
    "Mission: Dispatch the drone from {s} to {g}, then descend.",
    "Head from {s} to {g}, replan if obstructed.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Mission: Control the drone from {s} to {g}, then finish by landing.",
    "Dispatch from {s} to {g}, avoiding obstacles.",
    "Head from {s} to {g}, replan if unsafe.",
    "Dispatch the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep constant height.",
    "Objective: Control from {s} to {g} and touch down.",
    "Move from {s} to {g}, maintaining constant height.",
    "Head from {s} to {g}, avoiding no-fly zones.",
    "Dispatch the UAV from {s} to {g}.",
    "Head from {s} to {g}, replan if unsafe.",
    "Send the UAV from {s} to {g}.",
    "Task: Pilot between {s} and {g}, stay cautious.",
    "Survey the area from {s} until reaching {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Head from {s} to {g}, replan if occupied.",
    "Survey the area from {s} until reaching {g}.",
    "Direct from {s} to {g}, maintaining safe altitude.",
    "Go from {s} to {g}, maintaining altitude 1.0 meters.",
    "Head from {s} to {g}, replan if occupied.",
    "Head from {s} to {g}, replan if obstructed.",
    "Head the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep constant height.",
    "Operate the UAV from {s} to {g}.",
    "Mission: Navigate the drone from {s} to {g}, then return safely.",
    "Send from {s} to {g}, maintaining altitude 1.0 meters.",
    "Start at {s}, Control to {g}, then land.",
    "Mission: Move the drone from {s} to {g}, then land.",
    "Head from {s} to {g}, replan if occupied.",
    "Start at {s}, Fly to {g}, then touch down.",
    "Send the UAV from {s} to {g}.",
    "Task: Dispatch between {s} and {g}, stay cautious.",
    "Task: Direct between {s} and {g}, stay safe.",
    "Start at {s}, Fly to {g}, then land.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Pilot the UAV from {s} to {g}.",
    "Task: Move between {s} and {g}, stay clear of hazards.",
    "Survey the area from {s} until reaching {g}.",
    "Task: Send between {s} and {g}, stay within safe zones.",
    "Mission: Navigate the drone from {s} to {g}, then land.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Head from {s} to {g}, maintaining safe altitude.",
    "Mission: Move the drone from {s} to {g}, then descend.",
    "Pilot from {s} to {g}, maintaining 1 meter height.",
    "Control from {s} to {g}, avoiding no-fly zones.",
    "Task: Travel between {s} and {g}, stay cautious.",
    "Direct from {s} to {g}, avoiding obstacles.",
    "Scout path from {s} to {g}, keep constant height.",
    "Pilot from {s} to {g}, avoiding hazards.",
    "Objective: Direct from {s} to {g} and descend.",
    "Operate from {s} to {g}, maintaining safe altitude.",
    "Survey the area from {s} until reaching {g}.",
    "Send the UAV from {s} to {g}.",
    "Go from {s} to {g}, maintaining a steady altitude.",
    "Operate the UAV from {s} to {g}.",
    "Head the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Navigate from {s} to {g}, avoiding danger areas.",
    "Task: Operate between {s} and {g}, stay clear of hazards.",
    "Mission: Fly the drone from {s} to {g}, then return safely.",
    "Task: Go between {s} and {g}, stay within safe zones.",
    "Task: Head between {s} and {g}, stay within safe zones.",
    "Task: Dispatch between {s} and {g}, stay within safe zones.",
    "Start at {s}, Send to {g}, then return safely.",
    "Objective: Direct from {s} to {g} and touch down.",
    "Survey the area from {s} until reaching {g}.",
    "Travel from {s} to {g}, maintaining safe altitude.",
    "Scout path from {s} to {g}, keep constant height.",
    "Fly from {s} to {g}, maintaining altitude 1.0 meters.",
    "Survey the area from {s} until reaching {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Dispatch from {s} to {g}, maintaining low altitude.",
    "Objective: Fly from {s} to {g} and finish by landing.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Scout path from {s} to {g}, keep constant height.",
    "Pilot the UAV from {s} to {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Objective: Operate from {s} to {g} and land.",
    "Travel the UAV from {s} to {g}.",
    "Mission: Control the drone from {s} to {g}, then touch down.",
    "Fly from {s} to {g}, avoiding barriers.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Survey the area from {s} until reaching {g}.",
    "Objective: Move from {s} to {g} and descend.",
    "Start at {s}, Head to {g}, then return safely.",
    "Pilot the UAV from {s} to {g}.",
    "Start at {s}, Send to {g}, then land.",
    "Send the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Task: Head between {s} and {g}, stay clear of hazards.",
    "Go from {s} to {g}, avoiding danger areas.",
    "Direct from {s} to {g}, maintaining low altitude.",
    "Move from {s} to {g}, avoiding barriers.",
    "Start at {s}, Navigate to {g}, then touch down.",
    "Objective: Go from {s} to {g} and return safely.",
    "Survey the area from {s} until reaching {g}.",
    "Head from {s} to {g}, maintaining low altitude.",
    "Mission: Operate the drone from {s} to {g}, then descend.",
    "Mission: Pilot the drone from {s} to {g}, then finish by landing.",
    "Survey the area from {s} until reaching {g}.",
    "Navigate from {s} to {g}, avoiding barriers.",
    "Head from {s} to {g}, replan if blocked.",
    "Task: Send between {s} and {g}, stay within safe zones.",
    "Mission: Head the drone from {s} to {g}, then finish by landing.",
    "Move the UAV from {s} to {g}.",
    "Mission: Control the drone from {s} to {g}, then finish by landing.",
    "Move from {s} to {g}, avoiding barriers.",
    "Control from {s} to {g}, avoiding restricted regions.",
    "Survey the area from {s} until reaching {g}.",
    "Control the UAV from {s} to {g}.",
    "Mission: Navigate the drone from {s} to {g}, then land.",
    "Mission: Pilot the drone from {s} to {g}, then finish by landing.",
    "Mission: Head the drone from {s} to {g}, then return safely.",
    "Start at {s}, Dispatch to {g}, then touch down.",
    "Task: Dispatch between {s} and {g}, stay safe.",
    "Direct from {s} to {g}, maintaining constant height.",
    "Head from {s} to {g}, replan if occupied.",
    "Direct from {s} to {g}, avoiding hazards.",
    "Head from {s} to {g}, replan if obstructed.",
    "Head from {s} to {g}, replan if occupied.",
    "Objective: Navigate from {s} to {g} and descend.",
    "Direct from {s} to {g}, maintaining altitude 1.0 meters.",
    "Send from {s} to {g}, avoiding hazards.",
    "Start at {s}, Operate to {g}, then touch down.",
    "Start at {s}, Go to {g}, then return safely.",
    "Head from {s} to {g}, replan if occupied.",
    "Objective: Direct from {s} to {g} and return safely.",
    "Start at {s}, Fly to {g}, then finish by landing.",
    "Start at {s}, Fly to {g}, then finish by landing.",
    "Objective: Navigate from {s} to {g} and touch down.",
    "Task: Control between {s} and {g}, stay away from danger.",
    "Task: Fly between {s} and {g}, stay within safe zones.",
    "Head from {s} to {g}, replan if blocked.",
    "Head from {s} to {g}, replan if occupied.",
    "Survey the area from {s} until reaching {g}.",
    "Mission: Send the drone from {s} to {g}, then return safely.",
    "Go from {s} to {g}, maintaining constant height.",
    "Objective: Move from {s} to {g} and descend.",
    "Head from {s} to {g}, replan if obstructed.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Mission: Dispatch the drone from {s} to {g}, then descend.",
    "Start at {s}, Fly to {g}, then descend.",
    "Control from {s} to {g}, maintaining a steady altitude.",
    "Objective: Pilot from {s} to {g} and return safely.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Head from {s} to {g}, replan if obstructed.",
    "Dispatch from {s} to {g}, maintaining 1 meter height.",
    "Mission: Fly the drone from {s} to {g}, then descend.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Mission: Head the drone from {s} to {g}, then land.",
    "Task: Move between {s} and {g}, stay within safe zones.",
    "Survey the area from {s} until reaching {g}.",
    "Fly from {s} to {g}, maintaining altitude 1.0 meters.",
    "Travel the UAV from {s} to {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Task: Direct between {s} and {g}, stay away from danger.",
    "Move the UAV from {s} to {g}.",
    "Send the UAV from {s} to {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Objective: Head from {s} to {g} and descend.",
    "Start at {s}, Operate to {g}, then return safely.",
    "Mission: Control the drone from {s} to {g}, then return safely.",
    "Head the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep constant height.",
    "Objective: Operate from {s} to {g} and descend.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Objective: Travel from {s} to {g} and descend.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Start at {s}, Fly to {g}, then touch down.",
    "Survey the area from {s} until reaching {g}.",
    "Travel from {s} to {g}, maintaining 1 meter height.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Start at {s}, Head to {g}, then descend.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Operate from {s} to {g}, avoiding barriers.",
    "Pilot from {s} to {g}, maintaining safe altitude.",
    "Start at {s}, Direct to {g}, then land.",
    "Objective: Travel from {s} to {g} and return safely.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Task: Direct between {s} and {g}, stay clear of hazards.",
    "Head from {s} to {g}, replan if unsafe.",
    "Objective: Move from {s} to {g} and touch down.",
    "Operate from {s} to {g}, avoiding hazards.",
    "Objective: Head from {s} to {g} and land.",
    "Task: Fly between {s} and {g}, stay cautious.",
    "Start at {s}, Go to {g}, then return safely.",
    "Head from {s} to {g}, maintaining safe altitude.",
    "Mission: Navigate the drone from {s} to {g}, then land.",
    "Head from {s} to {g}, replan if obstructed.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Go from {s} to {g}, avoiding hazards.",
    "Move from {s} to {g}, maintaining low altitude.",
    "Go the UAV from {s} to {g}.",
    "Start at {s}, Fly to {g}, then return safely.",
    "Head from {s} to {g}, replan if not clear.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Travel from {s} to {g}, avoiding hazards.",
    "Send the UAV from {s} to {g}.",
    "Fly the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep constant height.",
    "Start at {s}, Operate to {g}, then land.",
    "Mission: Dispatch the drone from {s} to {g}, then return safely.",
    "Task: Direct between {s} and {g}, stay clear of hazards.",
    "Scout path from {s} to {g}, keep constant height.",
    "Operate the UAV from {s} to {g}.",
    "Start at {s}, Send to {g}, then touch down.",
    "Travel from {s} to {g}, maintaining 1 meter height.",
    "Head from {s} to {g}, replan if obstructed.",
    "Fly from {s} to {g}, maintaining safe altitude.",
    "Direct from {s} to {g}, maintaining safe altitude.",
    "Navigate from {s} to {g}, maintaining 1 meter height.",
    "Send from {s} to {g}, maintaining 1 meter height.",
    "Send from {s} to {g}, maintaining constant height.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Objective: Navigate from {s} to {g} and return safely.",
    "Fly the UAV from {s} to {g}.",
    "Mission: Travel the drone from {s} to {g}, then descend.",
    "Direct from {s} to {g}, maintaining altitude 1.0 meters.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Direct from {s} to {g}, maintaining a steady altitude.",
    "Task: Direct between {s} and {g}, stay within safe zones.",
    "Operate from {s} to {g}, maintaining safe altitude.",
    "Mission: Move the drone from {s} to {g}, then descend.",
    "Head from {s} to {g}, maintaining safe altitude.",
    "Head from {s} to {g}, maintaining low altitude.",
    "Task: Dispatch between {s} and {g}, stay clear of hazards.",
    "Survey the area from {s} until reaching {g}.",
    "Head the UAV from {s} to {g}.",
    "Operate from {s} to {g}, avoiding restricted regions.",
    "Objective: Send from {s} to {g} and land.",
    "Head from {s} to {g}, replan if obstructed.",
    "Head from {s} to {g}, replan if blocked.",
    "Mission: Go the drone from {s} to {g}, then touch down.",
    "Objective: Move from {s} to {g} and finish by landing.",
    "Task: Go between {s} and {g}, stay safe.",
    "Task: Send between {s} and {g}, stay cautious.",
    "Mission: Operate the drone from {s} to {g}, then land.",
    "Task: Direct between {s} and {g}, stay away from danger.",
    "Task: Pilot between {s} and {g}, stay away from danger.",
    "Start at {s}, Direct to {g}, then finish by landing.",
    "Mission: Fly the drone from {s} to {g}, then descend.",
    "Survey the area from {s} until reaching {g}.",
    "Travel from {s} to {g}, avoiding barriers.",
    "Head from {s} to {g}, replan if unsafe.",
    "Task: Move between {s} and {g}, stay safe.",
    "Head from {s} to {g}, replan if obstructed.",
    "Objective: Go from {s} to {g} and finish by landing.",
    "Head from {s} to {g}, replan if unsafe.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Scout path from {s} to {g}, keep constant height.",
    "Move from {s} to {g}, maintaining low altitude.",
    "Objective: Head from {s} to {g} and land.",
    "Start at {s}, Operate to {g}, then touch down.",
    "Objective: Travel from {s} to {g} and return safely.",
    "Dispatch the UAV from {s} to {g}.",
    "Mission: Send the drone from {s} to {g}, then land.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Direct from {s} to {g}, avoiding restricted regions.",
    "Mission: Head the drone from {s} to {g}, then descend.",
    "Objective: Travel from {s} to {g} and descend.",
    "Send from {s} to {g}, maintaining constant height.",
    "Objective: Travel from {s} to {g} and land.",
    "Start at {s}, Operate to {g}, then descend.",
    "Objective: Dispatch from {s} to {g} and finish by landing.",
    "Survey the area from {s} until reaching {g}.",
    "Head from {s} to {g}, replan if occupied.",
    "Mission: Navigate the drone from {s} to {g}, then return safely.",
    "Mission: Travel the drone from {s} to {g}, then finish by landing.",
    "Task: Fly between {s} and {g}, stay away from danger.",
    "Task: Move between {s} and {g}, stay safe.",
    "Mission: Pilot the drone from {s} to {g}, then touch down.",
    "Direct the UAV from {s} to {g}.",
    "Head from {s} to {g}, replan if blocked.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Head from {s} to {g}, replan if occupied.",
    "Survey the area from {s} until reaching {g}.",
    "Head from {s} to {g}, avoiding restricted regions.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Operate from {s} to {g}, avoiding barriers.",
    "Navigate from {s} to {g}, avoiding barriers.",
    "Mission: Navigate the drone from {s} to {g}, then touch down.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Operate from {s} to {g}, maintaining constant height.",
    "Start at {s}, Pilot to {g}, then descend.",
    "Pilot from {s} to {g}, maintaining constant height.",
    "Start at {s}, Head to {g}, then finish by landing.",
    "Go from {s} to {g}, maintaining safe altitude.",
    "Objective: Fly from {s} to {g} and land.",
    "Start at {s}, Travel to {g}, then touch down.",
    "Mission: Pilot the drone from {s} to {g}, then touch down.",
    "Fly from {s} to {g}, avoiding danger areas.",
    "Mission: Pilot the drone from {s} to {g}, then touch down.",
    "Send the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Objective: Move from {s} to {g} and finish by landing.",
    "Objective: Move from {s} to {g} and finish by landing.",
    "Navigate from {s} to {g}, avoiding barriers.",
    "Dispatch the UAV from {s} to {g}.",
    "Go from {s} to {g}, avoiding no-fly zones.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Start at {s}, Fly to {g}, then touch down.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Task: Pilot between {s} and {g}, stay safe.",
    "Navigate from {s} to {g}, maintaining altitude 1.0 meters.",
    "Survey the area from {s} until reaching {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Direct from {s} to {g}, avoiding no-fly zones.",
    "Head from {s} to {g}, maintaining altitude 1.0 meters.",
    "Start at {s}, Fly to {g}, then land.",
    "Head from {s} to {g}, replan if not clear.",
    "Direct from {s} to {g}, avoiding obstacles.",
    "Task: Operate between {s} and {g}, stay safe.",
    "Head from {s} to {g}, replan if occupied.",
    "Start at {s}, Control to {g}, then land.",
    "Operate from {s} to {g}, avoiding restricted regions.",
    "Head from {s} to {g}, replan if blocked.",
    "Head the UAV from {s} to {g}.",
    "Direct from {s} to {g}, maintaining a steady altitude.",
    "Task: Navigate between {s} and {g}, stay safe.",
    "Start at {s}, Head to {g}, then return safely.",
    "Move the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Head from {s} to {g}, replan if obstructed.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Head from {s} to {g}, replan if not clear.",
    "Task: Dispatch between {s} and {g}, stay safe.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Mission: Send the drone from {s} to {g}, then touch down.",
    "Direct from {s} to {g}, avoiding obstacles.",
    "Control from {s} to {g}, maintaining safe altitude.",
    "Direct from {s} to {g}, avoiding hazards.",
    "Survey the area from {s} until reaching {g}.",
    "Mission: Navigate the drone from {s} to {g}, then return safely.",
    "Control from {s} to {g}, avoiding restricted regions.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Head from {s} to {g}, replan if unsafe.",
    "Survey the area from {s} until reaching {g}.",
    "Task: Send between {s} and {g}, stay cautious.",
    "Dispatch from {s} to {g}, maintaining low altitude.",
    "Control the UAV from {s} to {g}.",
    "Navigate the UAV from {s} to {g}.",
    "Head from {s} to {g}, replan if not clear.",
    "Task: Travel between {s} and {g}, stay within safe zones.",
    "Start at {s}, Head to {g}, then return safely.",
    "Fly the UAV from {s} to {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Go from {s} to {g}, maintaining 1 meter height.",
    "Head from {s} to {g}, replan if not clear.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Travel from {s} to {g}, maintaining a steady altitude.",
    "Survey the area from {s} until reaching {g}.",
    "Objective: Move from {s} to {g} and touch down.",
    "Pilot from {s} to {g}, maintaining 1 meter height.",
    "Task: Pilot between {s} and {g}, stay away from danger.",
    "Objective: Travel from {s} to {g} and descend.",
    "Fly from {s} to {g}, maintaining altitude 1.0 meters.",
    "Objective: Control from {s} to {g} and land.",
    "Move from {s} to {g}, maintaining a steady altitude.",
    "Head from {s} to {g}, avoiding barriers.",
    "Move the UAV from {s} to {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Objective: Head from {s} to {g} and return safely.",
    "Navigate from {s} to {g}, maintaining constant height.",
    "Mission: Pilot the drone from {s} to {g}, then touch down.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Objective: Control from {s} to {g} and touch down.",
    "Direct the UAV from {s} to {g}.",
    "Objective: Travel from {s} to {g} and return safely.",
    "Task: Direct between {s} and {g}, stay within safe zones.",
    "Head from {s} to {g}, replan if unsafe.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Head from {s} to {g}, replan if occupied.",
    "Mission: Direct the drone from {s} to {g}, then touch down.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Operate from {s} to {g}, avoiding barriers.",
    "Head from {s} to {g}, replan if not clear.",
    "Navigate from {s} to {g}, maintaining constant height.",
    "Operate from {s} to {g}, avoiding obstacles.",
    "Mission: Go the drone from {s} to {g}, then touch down.",
    "Mission: Travel the drone from {s} to {g}, then touch down.",
    "Travel from {s} to {g}, avoiding danger areas.",
    "Scout path from {s} to {g}, keep constant height.",
    "Navigate the UAV from {s} to {g}.",
    "Start at {s}, Direct to {g}, then touch down.",
    "Objective: Navigate from {s} to {g} and touch down.",
    "Fly the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Task: Pilot between {s} and {g}, stay safe.",
    "Direct from {s} to {g}, maintaining altitude 1.0 meters.",
    "Objective: Send from {s} to {g} and touch down.",
    "Start at {s}, Navigate to {g}, then land.",
    "Direct from {s} to {g}, avoiding danger areas.",
    "Pilot the UAV from {s} to {g}.",
    "Task: Dispatch between {s} and {g}, stay safe.",
    "Task: Control between {s} and {g}, stay safe.",
    "Task: Go between {s} and {g}, stay cautious.",
    "Travel from {s} to {g}, maintaining a steady altitude.",
    "Send from {s} to {g}, avoiding barriers.",
    "Start at {s}, Control to {g}, then finish by landing.",
    "Mission: Fly the drone from {s} to {g}, then land.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Objective: Move from {s} to {g} and finish by landing.",
    "Objective: Head from {s} to {g} and land.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Mission: Control the drone from {s} to {g}, then finish by landing.",
    "Survey the area from {s} until reaching {g}.",
    "Head from {s} to {g}, maintaining safe altitude.",
    "Scout path from {s} to {g}, keep constant height.",
    "Start at {s}, Control to {g}, then descend.",
    "Send from {s} to {g}, avoiding barriers.",
    "Task: Direct between {s} and {g}, stay clear of hazards.",
    "Start at {s}, Move to {g}, then touch down.",
    "Objective: Go from {s} to {g} and touch down.",
    "Go from {s} to {g}, maintaining safe altitude.",
    "Control the UAV from {s} to {g}.",
    "Direct from {s} to {g}, avoiding barriers.",
    "Start at {s}, Send to {g}, then land.",
    "Survey the area from {s} until reaching {g}.",
    "Start at {s}, Head to {g}, then land.",
    "Pilot the UAV from {s} to {g}.",
    "Objective: Control from {s} to {g} and land.",
    "Task: Head between {s} and {g}, stay clear of hazards.",
    "Go from {s} to {g}, maintaining safe altitude.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Task: Move between {s} and {g}, stay safe.",
    "Start at {s}, Pilot to {g}, then touch down.",
    "Task: Go between {s} and {g}, stay within safe zones.",
    "Direct from {s} to {g}, maintaining 1 meter height.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Navigate the UAV from {s} to {g}.",
    "Objective: Fly from {s} to {g} and return safely.",
    "Head the UAV from {s} to {g}.",
    "Task: Control between {s} and {g}, stay safe.",
    "Survey the area from {s} until reaching {g}.",
    "Pilot from {s} to {g}, avoiding restricted regions.",
    "Head from {s} to {g}, replan if obstructed.",
    "Survey the area from {s} until reaching {g}.",
    "Task: Dispatch between {s} and {g}, stay clear of hazards.",
    "Start at {s}, Navigate to {g}, then touch down.",
    "Dispatch from {s} to {g}, maintaining low altitude.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Mission: Control the drone from {s} to {g}, then touch down.",
    "Task: Dispatch between {s} and {g}, stay away from danger.",
    "Fly from {s} to {g}, maintaining a steady altitude.",
    "Start at {s}, Operate to {g}, then finish by landing.",
    "Survey the area from {s} until reaching {g}.",
    "Operate the UAV from {s} to {g}.",
    "Mission: Send the drone from {s} to {g}, then descend.",
    "Head from {s} to {g}, replan if not clear.",
    "Task: Travel between {s} and {g}, stay clear of hazards.",
    "Dispatch from {s} to {g}, avoiding barriers.",
    "Direct from {s} to {g}, maintaining a steady altitude.",
    "Start at {s}, Direct to {g}, then return safely.",
    "Start at {s}, Travel to {g}, then touch down.",
    "Head the UAV from {s} to {g}.",
    "Direct from {s} to {g}, maintaining a steady altitude.",
    "Task: Direct between {s} and {g}, stay clear of hazards.",
    "Start at {s}, Travel to {g}, then return safely.",
    "Mission: Travel the drone from {s} to {g}, then land.",
    "Head from {s} to {g}, replan if not clear.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Mission: Travel the drone from {s} to {g}, then descend.",
    "Head the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep constant height.",
    "Travel the UAV from {s} to {g}.",
    "Mission: Navigate the drone from {s} to {g}, then finish by landing.",
    "Objective: Move from {s} to {g} and descend.",
    "Head from {s} to {g}, replan if occupied.",
    "Pilot from {s} to {g}, avoiding danger areas.",
    "Go from {s} to {g}, avoiding danger areas.",
    "Navigate from {s} to {g}, avoiding barriers.",
    "Scout path from {s} to {g}, keep constant height.",
    "Mission: Control the drone from {s} to {g}, then return safely.",
    "Dispatch from {s} to {g}, maintaining low altitude.",
    "Head from {s} to {g}, replan if blocked.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Fly from {s} to {g}, maintaining a steady altitude.",
    "Mission: Send the drone from {s} to {g}, then touch down.",
    "Head the UAV from {s} to {g}.",
    "Operate from {s} to {g}, maintaining safe altitude.",
    "Fly the UAV from {s} to {g}.",
    "Head from {s} to {g}, replan if occupied.",
    "Objective: Travel from {s} to {g} and descend.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Task: Send between {s} and {g}, stay within safe zones.",
    "Fly from {s} to {g}, avoiding no-fly zones.",
    "Control from {s} to {g}, avoiding no-fly zones.",
    "Go from {s} to {g}, avoiding hazards.",
    "Head from {s} to {g}, replan if occupied.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Task: Pilot between {s} and {g}, stay safe.",
    "Fly from {s} to {g}, maintaining altitude 1.0 meters.",
    "Survey the area from {s} until reaching {g}.",
    "Task: Go between {s} and {g}, stay clear of hazards.",
    "Travel from {s} to {g}, avoiding obstacles.",
    "Head from {s} to {g}, replan if not clear.",
    "Send from {s} to {g}, avoiding barriers.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Fly from {s} to {g}, avoiding barriers.",
    "Operate from {s} to {g}, avoiding danger areas.",
    "Send from {s} to {g}, avoiding danger areas.",
    "Task: Pilot between {s} and {g}, stay away from danger.",
    "Objective: Pilot from {s} to {g} and descend.",
    "Head from {s} to {g}, replan if blocked.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Move the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Pilot the UAV from {s} to {g}.",
    "Task: Direct between {s} and {g}, stay safe.",
    "Mission: Go the drone from {s} to {g}, then land.",
    "Head from {s} to {g}, replan if occupied.",
    "Scout path from {s} to {g}, keep constant height.",
    "Navigate the UAV from {s} to {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Navigate from {s} to {g}, maintaining a steady altitude.",
    "Navigate from {s} to {g}, avoiding obstacles.",
    "Objective: Go from {s} to {g} and descend.",
    "Objective: Head from {s} to {g} and descend.",
    "Control from {s} to {g}, maintaining altitude 1.0 meters.",
    "Mission: Pilot the drone from {s} to {g}, then touch down.",
    "Head the UAV from {s} to {g}.",
    "Go from {s} to {g}, maintaining a steady altitude.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Objective: Direct from {s} to {g} and return safely.",
    "Objective: Move from {s} to {g} and touch down.",
    "Control from {s} to {g}, avoiding no-fly zones.",
    "Mission: Direct the drone from {s} to {g}, then finish by landing.",
    "Operate the UAV from {s} to {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Task: Operate between {s} and {g}, stay clear of hazards.",
    "Head from {s} to {g}, replan if obstructed.",
    "Start at {s}, Pilot to {g}, then return safely.",
    "Head from {s} to {g}, replan if not clear.",
    "Head from {s} to {g}, replan if unsafe.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Objective: Direct from {s} to {g} and touch down.",
    "Mission: Go the drone from {s} to {g}, then descend.",
    "Survey the area from {s} until reaching {g}.",
    "Start at {s}, Move to {g}, then finish by landing.",
    "Direct from {s} to {g}, avoiding restricted regions.",
    "Objective: Control from {s} to {g} and finish by landing.",
    "Objective: Control from {s} to {g} and land.",
    "Task: Move between {s} and {g}, stay within safe zones.",
    "Task: Pilot between {s} and {g}, stay cautious.",
    "Start at {s}, Navigate to {g}, then touch down.",
    "Start at {s}, Move to {g}, then land.",
    "Move the UAV from {s} to {g}.",
    "Task: Navigate between {s} and {g}, stay safe.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Travel the UAV from {s} to {g}.",
    "Mission: Pilot the drone from {s} to {g}, then touch down.",
    "Start at {s}, Go to {g}, then descend.",
    "Task: Dispatch between {s} and {g}, stay cautious.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Task: Direct between {s} and {g}, stay cautious.",
    "Objective: Head from {s} to {g} and touch down.",
    "Direct from {s} to {g}, avoiding hazards.",
    "Go from {s} to {g}, avoiding danger areas.",
    "Navigate from {s} to {g}, maintaining altitude 1.0 meters.",
    "Objective: Go from {s} to {g} and land.",
    "Move from {s} to {g}, avoiding hazards.",
    "Mission: Go the drone from {s} to {g}, then finish by landing.",
    "Task: Control between {s} and {g}, stay safe.",
    "Task: Control between {s} and {g}, stay clear of hazards.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Fly from {s} to {g}, avoiding barriers.",
    "Mission: Direct the drone from {s} to {g}, then land.",
    "Dispatch from {s} to {g}, maintaining altitude 1.0 meters.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Head from {s} to {g}, replan if unsafe.",
    "Task: Move between {s} and {g}, stay within safe zones.",
    "Objective: Send from {s} to {g} and touch down.",
    "Send from {s} to {g}, maintaining safe altitude.",
    "Task: Send between {s} and {g}, stay safe.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Start at {s}, Send to {g}, then finish by landing.",
    "Scout path from {s} to {g}, keep constant height.",
    "Send the UAV from {s} to {g}.",
    "Move from {s} to {g}, avoiding danger areas.",
    "Control the UAV from {s} to {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Move the UAV from {s} to {g}.",
    "Head from {s} to {g}, replan if blocked.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Objective: Fly from {s} to {g} and descend.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Objective: Operate from {s} to {g} and return safely.",
    "Start at {s}, Move to {g}, then return safely.",
    "Head the UAV from {s} to {g}.",
    "Task: Move between {s} and {g}, stay within safe zones.",
    "Direct the UAV from {s} to {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Task: Dispatch between {s} and {g}, stay away from danger.",
    "Start at {s}, Head to {g}, then return safely.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Mission: Go the drone from {s} to {g}, then descend.",
    "Move from {s} to {g}, avoiding restricted regions.",
    "Task: Operate between {s} and {g}, stay cautious.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Pilot the UAV from {s} to {g}.",
    "Task: Go between {s} and {g}, stay within safe zones.",
    "Head from {s} to {g}, replan if blocked.",
    "Task: Pilot between {s} and {g}, stay within safe zones.",
    "Task: Dispatch between {s} and {g}, stay within safe zones.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Fly from {s} to {g}, avoiding no-fly zones.",
    "Head from {s} to {g}, replan if blocked.",
    "Mission: Dispatch the drone from {s} to {g}, then touch down.",
    "Survey the area from {s} until reaching {g}.",
    "Mission: Send the drone from {s} to {g}, then touch down.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Navigate the UAV from {s} to {g}.",
    "Move the UAV from {s} to {g}.",
    "Objective: Go from {s} to {g} and land.",
    "Go the UAV from {s} to {g}.",
    "Objective: Travel from {s} to {g} and finish by landing.",
    "Survey the area from {s} until reaching {g}.",
    "Head from {s} to {g}, replan if occupied.",
    "Objective: Fly from {s} to {g} and finish by landing.",
    "Dispatch from {s} to {g}, avoiding no-fly zones.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Dispatch from {s} to {g}, maintaining 1 meter height.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Survey the area from {s} until reaching {g}.",
    "Travel from {s} to {g}, maintaining low altitude.",
    "Operate the UAV from {s} to {g}.",
    "Head from {s} to {g}, replan if not clear.",
    "Operate the UAV from {s} to {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep constant height.",
    "Control from {s} to {g}, maintaining 1 meter height.",
    "Move from {s} to {g}, maintaining 1 meter height.",
    "Operate from {s} to {g}, maintaining altitude 1.0 meters.",
    "Head from {s} to {g}, replan if unsafe.",
    "Objective: Fly from {s} to {g} and return safely.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Objective: Operate from {s} to {g} and touch down.",
    "Objective: Send from {s} to {g} and finish by landing.",
    "Head from {s} to {g}, replan if blocked.",
    "Control from {s} to {g}, avoiding no-fly zones.",
    "Head from {s} to {g}, replan if obstructed.",
    "Head from {s} to {g}, replan if obstructed.",
    "Start at {s}, Travel to {g}, then touch down.",
    "Mission: Navigate the drone from {s} to {g}, then touch down.",
    "Head from {s} to {g}, replan if obstructed.",
    "Scout path from {s} to {g}, keep constant height.",
    "Task: Dispatch between {s} and {g}, stay away from danger.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Objective: Operate from {s} to {g} and return safely.",
    "Mission: Fly the drone from {s} to {g}, then descend.",
    "Task: Direct between {s} and {g}, stay within safe zones.",
    "Dispatch from {s} to {g}, maintaining altitude 1.0 meters.",
    "Head from {s} to {g}, maintaining safe altitude.",
    "Go from {s} to {g}, maintaining 1 meter height.",
    "Mission: Travel the drone from {s} to {g}, then finish by landing.",
    "Task: Operate between {s} and {g}, stay within safe zones.",
    "Mission: Control the drone from {s} to {g}, then touch down.",
    "Task: Travel between {s} and {g}, stay away from danger.",
    "Start at {s}, Dispatch to {g}, then descend.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Mission: Travel the drone from {s} to {g}, then land.",
    "Objective: Navigate from {s} to {g} and touch down.",
    "Head from {s} to {g}, replan if occupied.",
    "Task: Go between {s} and {g}, stay safe.",
    "Fly the UAV from {s} to {g}.",
    "Task: Control between {s} and {g}, stay cautious.",
    "Mission: Dispatch the drone from {s} to {g}, then descend.",
    "Dispatch from {s} to {g}, avoiding barriers.",
    "Navigate the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep low altitude.",
    "Task: Operate between {s} and {g}, stay cautious.",
    "Task: Go between {s} and {g}, stay cautious.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Task: Travel between {s} and {g}, stay away from danger.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Control from {s} to {g}, maintaining a steady altitude.",
    "Mission: Operate the drone from {s} to {g}, then land.",
    "Control from {s} to {g}, avoiding danger areas.",
    "Start at {s}, Move to {g}, then finish by landing.",
    "Head from {s} to {g}, replan if occupied.",
    "Start at {s}, Move to {g}, then return safely.",
    "Objective: Move from {s} to {g} and finish by landing.",
    "Objective: Head from {s} to {g} and touch down.",
    "Head from {s} to {g}, replan if not clear.",
    "Start at {s}, Fly to {g}, then finish by landing.",
    "Operate from {s} to {g}, maintaining altitude 1.0 meters.",
    "Survey the area from {s} until reaching {g}.",
    "Pilot the UAV from {s} to {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Objective: Travel from {s} to {g} and land.",
    "Mission: Dispatch the drone from {s} to {g}, then finish by landing.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Start at {s}, Direct to {g}, then return safely.",
    "Head from {s} to {g}, replan if occupied.",
    "Dispatch from {s} to {g}, maintaining constant height.",
    "Head from {s} to {g}, replan if not clear.",
    "Head from {s} to {g}, replan if obstructed.",
    "Survey the area from {s} until reaching {g}.",
    "Survey the area from {s} until reaching {g}.",
    "Travel from {s} to {g}, maintaining altitude 1.0 meters.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Task: Control between {s} and {g}, stay safe.",
    "Task: Travel between {s} and {g}, stay cautious.",
    "Survey the area from {s} until reaching {g}.",
    "Head from {s} to {g}, replan if blocked.",
    "Task: Control between {s} and {g}, stay safe.",
    "Objective: Move from {s} to {g} and descend.",
    "Mission: Move the drone from {s} to {g}, then land.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Objective: Go from {s} to {g} and land.",
    "Task: Move between {s} and {g}, stay safe.",
    "Head from {s} to {g}, replan if not clear.",
    "Move the UAV from {s} to {g}.",
    "Start at {s}, Pilot to {g}, then touch down.",
    "Start at {s}, Travel to {g}, then touch down.",
    "Head from {s} to {g}, replan if obstructed.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Pilot from {s} to {g}, avoiding restricted regions.",
    "Survey the area from {s} until reaching {g}.",
    "Move the UAV from {s} to {g}.",
    "Start at {s}, Navigate to {g}, then descend.",
    "Survey the area from {s} until reaching {g}.",
    "Head from {s} to {g}, replan if blocked.",
    "Move from {s} to {g}, avoiding obstacles.",
    "Scout path from {s} to {g}, keep constant height.",
    "Objective: Travel from {s} to {g} and touch down.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Objective: Navigate from {s} to {g} and descend.",
    "Control from {s} to {g}, avoiding obstacles.",
    "Task: Fly between {s} and {g}, stay safe.",
    "Head from {s} to {g}, replan if obstructed.",
    "Go the UAV from {s} to {g}.",
    "Mission: Pilot the drone from {s} to {g}, then descend.",
    "Send from {s} to {g}, maintaining low altitude.",
    "Head from {s} to {g}, replan if occupied.",
    "Operate from {s} to {g}, avoiding danger areas.",
    "Mission: Fly the drone from {s} to {g}, then touch down.",
    "Objective: Navigate from {s} to {g} and land.",
    "Move from {s} to {g}, maintaining altitude 1.0 meters.",
    "Operate from {s} to {g}, avoiding danger areas.",
    "Start at {s}, Head to {g}, then land.",
    "Objective: Navigate from {s} to {g} and return safely.",
    "Mission: Control the drone from {s} to {g}, then land.",
    "Fly the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Head from {s} to {g}, replan if blocked.",
    "Task: Send between {s} and {g}, stay cautious.",
    "Scout path from {s} to {g}, keep altitude 1.0 meters.",
    "Pilot from {s} to {g}, maintaining safe altitude.",
    "Move from {s} to {g}, maintaining safe altitude.",
    "Start at {s}, Direct to {g}, then return safely.",
    "Scout path from {s} to {g}, keep 1 meter height.",
    "Operate the UAV from {s} to {g}.",
    "Scout path from {s} to {g}, keep safe altitude.",
    "Survey the area from {s} until reaching {g}.",
    "Scout path from {s} to {g}, keep a steady altitude.",
    "Task: Send between {s} and {g}, stay away from danger.",
]